name: Build Kernel on GitHub Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/neutron-projects/docker-image:arch-minimal
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Prepare Toolchain
      run: bash scripts/hani-ci.sh --tools

    - name: Build hanikrnl.
      run: bash scripts/hani-ci.sh --build

    - name: Upload kernel
      uses: actions/upload-artifact@v4
      with:
        name: hanikrnl
        path: 4.19-hanikrnl.sd-*-chime*.zip
